[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "epr-mcp-server"
version = "0.1.0"
description = "MCP server for EPR workshop"
dependencies = [
    "httpx",
    "mcp",
]

